{% set version = "0.11.0" %}
{% set python_min = "3.10" %}

package:
  name: pygfx
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pygfx/pygfx-{{ version }}.tar.gz
  sha256: 29773e36bb62526cbc696a217008580cdce9d0c8cde3f0fa3db1b4bb6f47adfd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - flit-core
  run:
    - python >={{ python_min }}
    - rendercanvas >=2
    - numpy
    - wgpu-py >=0.19.0,<0.23.0a
    - pylinalg >=0.6.7,<0.7.0a
    - freetype-py
    - uharfbuzz
    - jinja2
    - hsluv >=5.0.0,<6.0.0a

test:
  imports:
    - pygfx
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check
about:
  home: https://github.com/pygfx/pygfx
  summary: "Pygfx' purpose is to bring powerful and reliable visualization to the Python world. 🚀"
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hmaarrfk
