{% set version = "0.15.2" %}
{% set python_min = "3.10" %}

package:
  name: pygfx
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pygfx/pygfx-{{ version }}.tar.gz
  sha256: fdec0a4751443b68f6c484f70a56f31bfd84169c08d3701e037c9d586d4afe2b

build:
  noarch: python
  script: 
    # The rendercanvas breakage was somewhat hard for a few people.
    # However, i don't think it is worth constraining too much
    # Remove the constraint on rendercanvas, let downstream project constrain themselves.
    # https://github.com/pygfx/pygfx/commit/bf2d32983d44e5ddedd47df7edf0ebb33f8f9097
    - sed -i '' '/"rendercanvas >=/d' pyproject.toml
    - {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - flit-core
  run:
    - python >={{ python_min }}
    - rendercanvas >=2.2
    - numpy
    - wgpu-py >=0.24.0,<0.28
    - pylinalg >=0.6.8,<0.7.0
    - freetype-py
    - uharfbuzz
    - jinja2
    - hsluv >=5.0.0

test:
  imports:
    - pygfx
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check
about:
  home: https://github.com/pygfx/pygfx
  summary: "Pygfx' purpose is to bring powerful and reliable visualization to the Python world. 🚀"
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hmaarrfk
