{% set version = "0.7.0" %}

package:
  name: pygfx
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pygfx/pygfx-{{ version }}.tar.gz
  sha256: c29a58dfb16ab2439f36afd0ef7731aac1d5fdf5881c680338ef01964fb4a1e1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - flit-core
  run:
    - python >={{ python_min }}
    - numpy
    - wgpu-py >=0.19.0,<0.20.0a
    - pylinalg >=0.4.1,<0.5.0a
    - freetype-py
    - uharfbuzz
    - jinja2

test:
  imports:
    - pygfx
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check
about:
  home: https://github.com/pygfx/pygfx
  summary: "Pygfx' purpose is to bring powerful and reliable visualization to the Python world. 🚀"
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hmaarrfk
