{% set version = "0.15.0" %}
{% set python_min = "3.10" %}

package:
  name: pygfx
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pygfx/pygfx-{{ version }}.tar.gz
  sha256: d8e17d3f8d340938e37ac0b3a6f24730efb4300bad127f98725865bb1caae13a
  patches:
    - 1229_allow_wgpu_0_27.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - flit-core
  run:
    - python >={{ python_min }}
    - rendercanvas >=2
    - numpy
    - wgpu-py >=0.24.0, <0.28
    - pylinalg >=0.6.8,<0.7.0
    - freetype-py
    - uharfbuzz
    - jinja2
    - hsluv >=5.0.0

test:
  imports:
    - pygfx
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check
about:
  home: https://github.com/pygfx/pygfx
  summary: "Pygfx' purpose is to bring powerful and reliable visualization to the Python world. 🚀"
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hmaarrfk
